# Generated by Django 5.1.7 on 2025-03-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('BR', 'Brasil'), ('US', 'Estados Unidos'), ('FR', 'França'), ('DE', 'Alemanha'), ('IT', 'Itália'), ('ES', 'Espanha'), ('UK', 'Reino Unido'), ('JP', 'Japão'), ('KR', 'Coreia do Sul'), ('CN', 'China'), ('IN', 'Índia'), ('RU', 'Rússia'), ('AU', 'Austrália'), ('MX', 'México'), ('AR', 'Argentina'), ('CA', 'Canadá')], max_length=100, null=True)),
            ],
        ),
    ]
