# Generated by Django 5.1.7 on 2025-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('BR', 'Brasil'), ('US', 'Estados Unidos'), ('FR', 'França'), ('DE', 'Alemanha'), ('IT', 'Itália'), ('ES', 'Espanha'), ('UK', 'Reino Unido'), ('JP', 'Japão'), ('KR', 'Coreia do Sul'), ('CN', 'China'), ('IN', 'Índia'), ('RU', 'Rússia'), ('AU', 'Austrália'), ('MX', 'México'), ('AR', 'Argentina'), ('CA', 'Canadá')], max_length=2, null=True),
        ),
    ]
